### ISSUE TITLE
這個可以不僅僅是Google Chrome extension嗎？

### ISSUE THREAD

**Issue by uqmeng** [doremi/seven#1]
能否升級成程式，不僅僅是Google Chrome extension，更加方便列印7-11交貨便的程式，可以輸入多個寄件代碼，實現大量列印嗎？感恩，謝謝~

**Comment by x86driver** [comment]
要做到這件事情，可能需要知道給定一組「寄件代碼」如何轉為「條碼」，目前這個 extension 只是根據 7-11 網站顯示出來的條碼做大小調整而已。

大量列印是有可能的, 但前提還是需要有「條碼」(而非代碼), 才能組合出一整頁的條碼來列印。

**Comment by uqmeng** [comment]
了解，謝謝回覆，感恩~
